### ISSUE TITLE
Installing and create akgfmaps vignettes

### ISSUE THREAD

**Issue by EmilyMarkowitz-NOAA** [sean-rohan-NOAA/akgfmaps#1]
Our Capstone Student was trying to install the akgfmaps package and got the following error: 

This code to install: 
devtools::install_github("sean-rohan-noaa/akgfmaps", build_vignettes = TRUE)

She got the following error:
Error: Failed to install 'akgfmaps' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 29-44 (make_nice_breaks.Rmd) 
E> Error: processing vignette 'make_nice_breaks.Rmd' failed with diagnostics:
E> unused argument (idp = idp)
E> --- failed re-building ‘make_nice_breaks.Rmd’
E> 
E> SUMMARY: processing the following files failed:
E>   ‘efficient_mapping.Rmd’ ‘make_idw.Rmd’ ‘make_nice_breaks.Rmd’
E> 
E> Error: Vignette re-building failed
E> Execution halted

We were able to get it to install with the following code, which does create the vignettes: 
withr::with_envvar(c(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"), remotes::install_github('sean-rohan-NOAA/akgfmaps', force = TRUE)) 

She is working on this R version and OS: 
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

Thanks!
Em

**Comment by sean-rohan-NOAA** [comment]
Vignette issue should be fixed.
